---
- name: Create VPC AWS
  ec2_vpc_net:
    name: Eric-Ansible-Test
    cidr_block: "{{ cidr_block }}"
    region: "{{ region }}"
    state: present
    tags:
      module: ec2_vpc_net
      this: works
    tenancy: default