---
- name: bcf spine configure
  bcf_switch:
    name: "{{ item.spine_name }}"
    fabric_role: spine
    mac: "{{ item.spine_mac }}"
    controller: '{{ inventory_hostname }}'
    state: present
    validate_certs: false
    access_token: rrD7nEDOIdD8sDizFUUyPDBPvietcMH-
  with_items: "{{ spines }}"

- name: bcf leaf configure
  bcf_switch:
    name: "{{ item.leaf_name }}"
    fabric_role: leaf
    leaf_group: "{{ item.leaf_group }}"
    mac: "{{ item.leaf_mac }}"
    controller: '{{ inventory_hostname }}'
    state: present
    validate_certs: false
    access_token: no
  with_items: "{{ leafs }}"