---
- name: Add an address object to the firewall
  panos_address:
    username: "admin"
    password: "admin"
    ip_address: '{{ inventory_hostname }}'
    address_name: 'h_1.1.1.1'
    address: '1.1.1.1'
    type: 'ip-netmask'
    description: 'This is the test ansible object'
    commit: true