---
- name: setup
  junos_config:
    lines:
      - delete firewall family inet filter Ansible-test term ansible then accept
      - set firewall family inet filter Ansible-test term ansible then accept
    host: "{{ inventory_hostname }}"
    transport: cli
