---
 - name: create SSH service
    panos_service:
      username: "{{ ANSIBLE_NET_USERNAME }}"
      password: "{{ ANSIBLE_NET_PASSWORD }}"
      ip_address: "192.168.1.1"
      password: "admin"
      service_name: "service-tcp-22"
      protocol: "tcp"
      port: "22"