---
- name: Force node offline
  bigip_node:
      server: "{{ server }}"
      state: "present"
      user: "{{ user }}"
      password: "{{ password }}"
      session_state: "{{ session_state }}"
      monitor_state: "disabled"
      partition: "Common"
      host: "{{ host }}"
      name: "{{ member_name }}"
