---
- name: enable ntp
  cisco_ucs_ntp:
    name: "{{ ntp_server }}"
    descr: Ansible managed NTP
    state: present
    ucs_ip: "{{ inventory_hostname }}"
    ucs_username: "ucspe"
    ucs_password: "ucspe"
